POST http://localhost:4000/app/order
Content-Type: application/json

{
    "buyer": "Egg",
    "seller": "Ass",
    "startTime": 1230,
    "endTime": 1300,
    "location": "De Neve",
    "price": 10,
}